version: '3.9'

services:
  dns-api:
    image: hometinker12/api-to-dns:latest
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - api-to-dns-data:/app/data
    restart: unless-stopped

volumes:
  api-to-dns-data:
